Repository moayoeats/moayoeats, pull requests merged in 2024-01, with the labels that each got.

#36 feat: PostErrorCode 생성
  src/main/java/com/moayo/moayoeats/domain/post/PostErrorCode.java
Labels: feature

#44 Feat/post entity and settings
  build.gradle
  src/main/java/com/moayo/moayoeats/domain/menu/entity/Menu.java
  src/main/java/com/moayo/moayoeats/domain/post/controller/PostController.java
  src/main/java/com/moayo/moayoeats/domain/post/entity/Post.java
  src/main/java/com/moayo/moayoeats/domain/post/repository/PostRepository.java
  src/main/java/com/moayo/moayoeats/domain/post/service/PostService.java
  src/main/java/com/moayo/moayoeats/domain/post/service/impl/PostServiceImpl.java
  src/main/java/com/moayo/moayoeats/global/entity/BaseTime.java
Labels: feature

#48 feat: Security 구현
  build.gradle
  src/main/java/com/moayo/moayoeats/global/config/WebSecurityConfig.java
  src/main/java/com/moayo/moayoeats/global/jwt/JwtUtil.java
  src/main/java/com/moayo/moayoeats/global/security/JwtAuthenticationFilter.java
  src/main/java/com/moayo/moayoeats/global/security/JwtAuthorizationFilter.java
  src/main/java/com/moayo/moayoeats/global/security/UserDetailsImpl.java
  src/main/java/com/moayo/moayoeats/global/security/UserDetailsServiceImpl.java
Labels: feature

#51 Feat: GlobalExceptionHandler 생성 #50
  src/main/java/com/moayo/moayoeats/global/exception/GlobalException.java
  src/main/java/com/moayo/moayoeats/global/exception/GlobalExceptionHandler.java
Labels: ⛏️refactor, feature

#54 Feat/create post
  src/main/java/com/moayo/moayoeats/domain/post/controller/PostController.java
  src/main/java/com/moayo/moayoeats/domain/post/dto/request/PostRequest.java
  src/main/java/com/moayo/moayoeats/domain/post/entity/CategoryEnum.java
  src/main/java/com/moayo/moayoeats/domain/post/entity/DeadlineEnum.java
  src/main/java/com/moayo/moayoeats/domain/post/entity/Post.java
  src/main/java/com/moayo/moayoeats/domain/post/exception/PostErrorCode.java
  src/main/java/com/moayo/moayoeats/domain/post/service/PostService.java
  src/main/java/com/moayo/moayoeats/domain/post/service/impl/PostServiceImpl.java
Labels: feature

#60 Feat/create post
  src/main/java/com/moayo/moayoeats/domain/post/dto/request/PostRequest.java
  src/main/java/com/moayo/moayoeats/domain/post/entity/DeadlineEnum.java
  src/main/java/com/moayo/moayoeats/domain/post/entity/Post.java
  src/main/java/com/moayo/moayoeats/domain/post/service/impl/PostServiceImpl.java
Labels: ⛏️refactor

#55 Feat/user signup
  .gitignore
  build.gradle
  src/main/java/com/moayo/moayoeats/domain/user/controller/UserController.java
  src/main/java/com/moayo/moayoeats/domain/user/dto/request/SignupRequest.java
  src/main/java/com/moayo/moayoeats/domain/user/entity/User.java
  src/main/java/com/moayo/moayoeats/domain/user/exception/UserDomainException.java
  src/main/java/com/moayo/moayoeats/domain/user/exception/UserErrorCode.java
  src/main/java/com/moayo/moayoeats/domain/user/repository/UserRepository.java
  src/main/java/com/moayo/moayoeats/domain/user/service/UserService.java
  src/main/java/com/moayo/moayoeats/domain/user/service/impl/UserServiceImpl.java
  src/main/java/com/moayo/moayoeats/global/dto/ApiResponse.java
  src/main/java/com/moayo/moayoeats/global/exception/GlobalException.java
  src/main/resources/application.yml
  src/test/java/com/moayo/moayoeats/MoayoeatsApplicationTests.java
Labels: feature

#70 Feat/add menu by author
  src/main/java/com/moayo/moayoeats/domain/menu/controller/MenuController.java
  src/main/java/com/moayo/moayoeats/domain/menu/dto/request/MenuRequest.java
  src/main/java/com/moayo/moayoeats/domain/menu/entity/Menu.java
  src/main/java/com/moayo/moayoeats/domain/menu/repository/MenuRepository.java
  src/main/java/com/moayo/moayoeats/domain/menu/service/MenuService.java
  src/main/java/com/moayo/moayoeats/domain/menu/service/impl/MenuServiceImpl.java
Labels: rename, feature

#75 Feat/user login
  src/main/java/com/moayo/moayoeats/domain/user/controller/UserController.java
  src/main/java/com/moayo/moayoeats/domain/user/dto/request/LoginRequest.java
  src/main/java/com/moayo/moayoeats/domain/user/exception/UserErrorCode.java
  src/main/java/com/moayo/moayoeats/domain/user/repository/UserRepository.java
  src/main/java/com/moayo/moayoeats/global/security/JwtAuthenticationFilter.java
  src/main/java/com/moayo/moayoeats/global/security/UserDetailsImpl.java
  src/main/java/com/moayo/moayoeats/global/security/UserDetailsServiceImpl.java
Labels: feature, fix

#76 feat: 유저 컨트롤러에 회원가입 성공 응답 추가
  src/main/java/com/moayo/moayoeats/domain/user/controller/UserController.java
Labels: feature

#78 fix: 사용자 예외처리 부분 globalException으로 수정
  src/main/java/com/moayo/moayoeats/domain/user/exception/UserDomainException.java
  src/main/java/com/moayo/moayoeats/domain/user/exception/UserErrorCode.java
  src/main/java/com/moayo/moayoeats/domain/user/service/impl/UserServiceImpl.java
  src/main/java/com/moayo/moayoeats/global/security/UserDetailsServiceImpl.java
Labels: fix

#79 refactor: Security 단 수정 #40
  src/main/java/com/moayo/moayoeats/global/config/WebSecurityConfig.java
Labels: fix

#77 feat: WebSocket 사용한 1:1 채팅 구현
  .gitignore
  build.gradle
  src/main/java/com/moayo/moayoeats/domain/chat/WebSocketHandler.java
  src/main/java/com/moayo/moayoeats/global/config/WebSocketConfig.java
Labels: feature

#81 Feat/userpost
  src/main/java/com/moayo/moayoeats/domain/menu/controller/MenuController.java
  src/main/java/com/moayo/moayoeats/domain/menu/entity/Menu.java
  src/main/java/com/moayo/moayoeats/domain/menu/service/MenuService.java
  src/main/java/com/moayo/moayoeats/domain/menu/service/impl/MenuServiceImpl.java
  src/main/java/com/moayo/moayoeats/domain/post/controller/PostController.java
  src/main/java/com/moayo/moayoeats/domain/post/service/PostService.java
  src/main/java/com/moayo/moayoeats/domain/post/service/impl/PostServiceImpl.java
  src/main/java/com/moayo/moayoeats/domain/userpost/entity/UserPost.java
  src/main/java/com/moayo/moayoeats/domain/userpost/entity/UserPostId.java
  src/main/java/com/moayo/moayoeats/domain/userpost/entity/UserPostRole.java
  src/main/java/com/moayo/moayoeats/domain/userpost/repository/UserPostRepository.java
Labels: ⛏️refactor, feature

#87 Feat/delete menu
  src/main/java/com/moayo/moayoeats/domain/menu/controller/MenuController.java
  src/main/java/com/moayo/moayoeats/domain/menu/dto/request/MenuDeleteRequest.java
  src/main/java/com/moayo/moayoeats/domain/menu/exception/MenuErrorCode.java
  src/main/java/com/moayo/moayoeats/domain/menu/service/MenuService.java
  src/main/java/com/moayo/moayoeats/domain/menu/service/impl/MenuServiceImpl.java
Labels: feature

#94 Feat/read all posts
  src/main/java/com/moayo/moayoeats/domain/menu/repository/MenuRepository.java
  src/main/java/com/moayo/moayoeats/domain/post/controller/PostController.java
  src/main/java/com/moayo/moayoeats/domain/post/dto/request/PostRequest.java
  src/main/java/com/moayo/moayoeats/domain/post/dto/response/BriefPostResponse.java
  src/main/java/com/moayo/moayoeats/domain/post/entity/Post.java
  src/main/java/com/moayo/moayoeats/domain/post/service/PostService.java
  src/main/java/com/moayo/moayoeats/domain/post/service/impl/PostServiceImpl.java
  src/main/java/com/moayo/moayoeats/domain/userpost/repository/UserPostRepository.java
Labels: ⛏️refactor, feature

#96 feat: UserPostErrorCode 생성
  src/main/java/com/moayo/moayoeats/domain/userpost/exception/UserPostErrorCode.java
Labels: feature

#98 feat: 모든 Exception AOP 처리 #97
  src/main/java/com/moayo/moayoeats/global/exception/GlobalExceptionHandler.java
Labels: feature

#95 Feat/chat multiple room
  src/main/java/com/moayo/moayoeats/domain/chat/ChatRoom.java
  src/main/java/com/moayo/moayoeats/domain/chat/WebSocketHandler.java
  src/main/java/com/moayo/moayoeats/domain/chat/controlloer/ChatController.java
  src/main/java/com/moayo/moayoeats/domain/chat/dto/ChatMessage.java
  src/main/java/com/moayo/moayoeats/domain/chat/service/ChatService.java
Labels: ⛏️refactor, feature

#110 Feat/offer apply participate
  src/main/java/com/moayo/moayoeats/MoayoeatsApplication.java
  src/main/java/com/moayo/moayoeats/domain/offer/controller/OfferController.java
  src/main/java/com/moayo/moayoeats/domain/offer/dto/request/OfferRequest.java
  src/main/java/com/moayo/moayoeats/domain/offer/entity/Offer.java
  src/main/java/com/moayo/moayoeats/domain/offer/exception/OfferErrorCode.java
  src/main/java/com/moayo/moayoeats/domain/offer/repository/OfferRepository.java
  src/main/java/com/moayo/moayoeats/domain/offer/service/OfferService.java
  src/main/java/com/moayo/moayoeats/domain/offer/service/impl/OfferServiceImpl.java
  src/main/java/com/moayo/moayoeats/domain/user/exception/UserErrorCode.java
Labels: feature

#122 Feat/read detailed post
  src/main/java/com/moayo/moayoeats/domain/menu/dto/response/MenuResponse.java
  src/main/java/com/moayo/moayoeats/domain/menu/dto/response/NickMenusResponse.java
  src/main/java/com/moayo/moayoeats/domain/menu/entity/Menu.java
  src/main/java/com/moayo/moayoeats/domain/post/controller/PostController.java
  src/main/java/com/moayo/moayoeats/domain/post/dto/response/DetailedPostResponse.java
  src/main/java/com/moayo/moayoeats/domain/post/entity/Post.java
  src/main/java/com/moayo/moayoeats/domain/post/service/PostService.java
  src/main/java/com/moayo/moayoeats/domain/post/service/impl/PostServiceImpl.java
  src/main/java/com/moayo/moayoeats/domain/userpost/exception/UserPostErrorCode.java
Labels: feature

#123 Feat/offer cancel participate
  src/main/java/com/moayo/moayoeats/domain/offer/controller/OfferController.java
  src/main/java/com/moayo/moayoeats/domain/offer/exception/OfferErrorCode.java
  src/main/java/com/moayo/moayoeats/domain/offer/repository/OfferRepository.java
  src/main/java/com/moayo/moayoeats/domain/offer/service/OfferService.java
  src/main/java/com/moayo/moayoeats/domain/offer/service/impl/OfferServiceImpl.java
Labels: ⛏️refactor, feature, fix

#130 Feat/read by category
  src/main/java/com/moayo/moayoeats/domain/post/controller/PostController.java
  src/main/java/com/moayo/moayoeats/domain/post/dto/request/PostCategoryRequest.java
  src/main/java/com/moayo/moayoeats/domain/post/entity/CategoryEnum.java
  src/main/java/com/moayo/moayoeats/domain/post/entity/Post.java
  src/main/java/com/moayo/moayoeats/domain/post/repository/PostRepository.java
  src/main/java/com/moayo/moayoeats/domain/post/service/PostService.java
  src/main/java/com/moayo/moayoeats/domain/post/service/impl/PostServiceImpl.java
Labels: ⛏️refactor, feature

#132 Feat/category validation
  src/main/java/com/moayo/moayoeats/domain/post/dto/request/PostCategoryRequest.java
  src/main/java/com/moayo/moayoeats/domain/post/exception/validator/Category.java
  src/main/java/com/moayo/moayoeats/domain/post/exception/validator/CategoryValidator.java
  src/main/java/com/moayo/moayoeats/domain/post/repository/PostRepository.java
  src/main/java/com/moayo/moayoeats/domain/post/service/impl/PostServiceImpl.java
  src/main/java/com/moayo/moayoeats/global/exception/GlobalExceptionHandler.java
Labels: ⛏️refactor, feature

#137 feat: 알림 목록 조회 #61
  src/main/java/com/moayo/moayoeats/domain/notification/controller/NotificationController.java
  src/main/java/com/moayo/moayoeats/domain/notification/dto/request/NotificationsRequest.java
  src/main/java/com/moayo/moayoeats/domain/notification/dto/response/NotificationsResponse.java
  src/main/java/com/moayo/moayoeats/domain/notification/entity/Notification.java
  src/main/java/com/moayo/moayoeats/domain/notification/entity/NotificationType.java
  src/main/java/com/moayo/moayoeats/domain/notification/event/Event.java
  src/main/java/com/moayo/moayoeats/domain/notification/event/NotificationListener.java
  src/main/java/com/moayo/moayoeats/domain/notification/repository/NotificationRepository.java
  src/main/java/com/moayo/moayoeats/domain/notification/service/NotificationService.java
  src/main/java/com/moayo/moayoeats/domain/notification/service/impl/NotificationServiceImpl.java
Labels: feature

#146 Feat/delete post
  src/main/java/com/moayo/moayoeats/domain/post/controller/PostController.java
  src/main/java/com/moayo/moayoeats/domain/post/dto/request/PostIdRequest.java
  src/main/java/com/moayo/moayoeats/domain/post/entity/Post.java
  src/main/java/com/moayo/moayoeats/domain/post/exception/PostErrorCode.java
  src/main/java/com/moayo/moayoeats/domain/post/repository/PostRepository.java
  src/main/java/com/moayo/moayoeats/domain/post/service/PostService.java
  src/main/java/com/moayo/moayoeats/domain/post/service/impl/PostServiceImpl.java
  src/main/java/com/moayo/moayoeats/domain/userpost/entity/UserPost.java
Labels: feature

#139 Feat/offer view participate
  src/main/java/com/moayo/moayoeats/domain/offer/controller/OfferController.java
  src/main/java/com/moayo/moayoeats/domain/offer/dto/response/OfferResponse.java
  src/main/java/com/moayo/moayoeats/domain/offer/repository/OfferRepository.java
  src/main/java/com/moayo/moayoeats/domain/offer/service/OfferService.java
  src/main/java/com/moayo/moayoeats/domain/offer/service/impl/OfferServiceImpl.java
  src/main/java/com/moayo/moayoeats/domain/post/entity/Post.java
  src/main/java/com/moayo/moayoeats/domain/post/exception/PostErrorCode.java
  src/main/java/com/moayo/moayoeats/domain/userpost/repository/UserPostRepository.java
Labels: ⛏️refactor, feature

#152 Feat/search
  src/main/java/com/moayo/moayoeats/domain/post/controller/PostController.java
  src/main/java/com/moayo/moayoeats/domain/post/dto/request/PostCategoryRequest.java
  src/main/java/com/moayo/moayoeats/domain/post/dto/request/PostRequest.java
  src/main/java/com/moayo/moayoeats/domain/post/dto/request/PostSearchRequest.java
  src/main/java/com/moayo/moayoeats/domain/post/entity/Post.java
  src/main/java/com/moayo/moayoeats/domain/post/repository/PostRepository.java
  src/main/java/com/moayo/moayoeats/domain/post/service/PostService.java
  src/main/java/com/moayo/moayoeats/domain/post/service/impl/PostServiceImpl.java
Labels: ⛏️refactor, chore, feature

#153 feat: Host는 참가신청 불가능하도록 기능 구현
  src/main/java/com/moayo/moayoeats/domain/offer/exception/OfferErrorCode.java
  src/main/java/com/moayo/moayoeats/domain/offer/service/impl/OfferServiceImpl.java
  src/main/java/com/moayo/moayoeats/domain/userpost/repository/UserPostRepository.java
Labels: feature

#166 Feat/post front
  src/main/java/com/moayo/moayoeats/domain/post/controller/PostController.java
  src/main/java/com/moayo/moayoeats/domain/post/service/PostService.java
  src/main/java/com/moayo/moayoeats/domain/post/service/impl/PostServiceImpl.java
  src/main/java/com/moayo/moayoeats/frontend/domain/post/controller/PostFrontController.java
  src/main/java/com/moayo/moayoeats/global/config/WebSecurityConfig.java
  src/main/resources/templates/post/createpost.html
Labels: feature

#158 Feat/offer approve participate
  src/main/java/com/moayo/moayoeats/backend/domain/chat/ChatRoom.java
  src/main/java/com/moayo/moayoeats/backend/domain/menu/controller/MenuController.java
  src/main/java/com/moayo/moayoeats/backend/domain/menu/entity/Menu.java
  src/main/java/com/moayo/moayoeats/backend/domain/menu/exception/MenuErrorCode.java
  src/main/java/com/moayo/moayoeats/backend/domain/menu/repository/MenuRepository.java
  src/main/java/com/moayo/moayoeats/backend/domain/notification/controller/NotificationController.java
  src/main/java/com/moayo/moayoeats/backend/domain/notification/dto/response/NotificationsResponse.java
  src/main/java/com/moayo/moayoeats/backend/domain/notification/entity/NotificationType.java
  src/main/java/com/moayo/moayoeats/backend/domain/notification/event/Event.java
  src/main/java/com/moayo/moayoeats/backend/domain/notification/event/NotificationListener.java
  src/main/java/com/moayo/moayoeats/backend/domain/notification/repository/NotificationRepository.java
  src/main/java/com/moayo/moayoeats/backend/domain/notification/service/NotificationService.java
  src/main/java/com/moayo/moayoeats/backend/domain/notification/service/impl/NotificationServiceImpl.java
  src/main/java/com/moayo/moayoeats/backend/domain/offer/controller/OfferController.java
  src/main/java/com/moayo/moayoeats/backend/domain/offer/service/OfferService.java
  src/main/java/com/moayo/moayoeats/backend/domain/offer/service/impl/OfferServiceImpl.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/dto/response/BriefPostResponse.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/dto/response/DetailedPostResponse.java
  src/main/java/com/moayo/moayoeats/backend/domain/user/repository/UserRepository.java
  src/main/java/com/moayo/moayoeats/backend/global/dto/ApiResponse.java
  src/main/java/com/moayo/moayoeats/backend/global/exception/ErrorCode.java
  src/main/java/com/moayo/moayoeats/backend/global/exception/GlobalException.java
  src/main/java/com/moayo/moayoeats/backend/global/exception/GlobalExceptionHandler.java
  src/main/java/com/moayo/moayoeats/backend/global/jwt/JwtUtil.java
  src/main/java/com/moayo/moayoeats/backend/global/security/JwtAuthorizationFilter.java
Labels: ⛏️refactor, feature

#184 Feat/close application
  src/main/java/com/moayo/moayoeats/backend/domain/menu/service/impl/MenuServiceImpl.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/controller/PostController.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/entity/Post.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/entity/PostStatusEnum.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/exception/PostErrorCode.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/service/PostService.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/service/impl/PostServiceImpl.java
Labels: feature

#195 Feat/complete order
  src/main/java/com/moayo/moayoeats/backend/domain/post/controller/PostController.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/entity/Post.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/exception/PostErrorCode.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/service/PostService.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/service/impl/PostServiceImpl.java
Labels: feature

#202 Feat/map api
  src/main/java/com/moayo/moayoeats/backend/domain/post/entity/Post.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/service/impl/PostServiceImpl.java
  src/main/java/com/moayo/moayoeats/frontend/domain/post/PostFrontController.java
  src/main/resources/templates/domain/post/createpost.html
Labels: feature

#204 Feat/offer reject participate
  src/main/java/com/moayo/moayoeats/backend/domain/offer/controller/OfferController.java
  src/main/java/com/moayo/moayoeats/backend/domain/offer/service/OfferService.java
  src/main/java/com/moayo/moayoeats/backend/domain/offer/service/impl/OfferServiceImpl.java
Labels: feature

#208 Feat/offer cancel after approval
  src/main/java/com/moayo/moayoeats/backend/domain/offer/controller/OfferController.java
  src/main/java/com/moayo/moayoeats/backend/domain/offer/service/OfferService.java
  src/main/java/com/moayo/moayoeats/backend/domain/offer/service/impl/OfferServiceImpl.java
Labels: ⛏️refactor, feature

#215 Feat/chat stomp
  src/main/java/com/moayo/moayoeats/backend/domain/chat/ChatRoom.java
  src/main/java/com/moayo/moayoeats/backend/domain/chat/WebSocketHandler.java
  src/main/java/com/moayo/moayoeats/backend/domain/chat/controlloer/ChatController.java
  src/main/java/com/moayo/moayoeats/backend/domain/chat/dto/ChatMessage.java
  src/main/java/com/moayo/moayoeats/backend/domain/chat/entity/ChatRoom.java
  src/main/java/com/moayo/moayoeats/backend/domain/chat/repository/ChatRoomRepository.java
  src/main/java/com/moayo/moayoeats/backend/domain/chat/service/ChatRoomService.java
  src/main/java/com/moayo/moayoeats/backend/domain/chat/service/ChatService.java
  src/main/java/com/moayo/moayoeats/backend/domain/chat/service/impl/ChatRoomServiceImpl.java
  src/main/java/com/moayo/moayoeats/backend/global/config/WebSocketConfig.java
Labels: ⛏️refactor, feature

#210 feat: Offer 서비스 참가신청 메서드에 post 상태 확인하는 로직 추가 #209
  src/main/java/com/moayo/moayoeats/backend/domain/offer/service/impl/OfferServiceImpl.java
Labels: feature

#226 Feat/receive order
  src/main/java/com/moayo/moayoeats/backend/domain/menu/entity/Menu.java
  src/main/java/com/moayo/moayoeats/backend/domain/menu/repository/MenuRepository.java
  src/main/java/com/moayo/moayoeats/backend/domain/order/entity/Order.java
  src/main/java/com/moayo/moayoeats/backend/domain/order/repository/OrderRepository.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/controller/PostController.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/entity/Post.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/service/PostService.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/service/impl/PostServiceImpl.java
Labels: ⛏️refactor, feature

#228 Feat/user info update
  src/main/java/com/moayo/moayoeats/backend/domain/user/controller/UserController.java
  src/main/java/com/moayo/moayoeats/backend/domain/user/dto/request/InfoUpdateRequest.java
  src/main/java/com/moayo/moayoeats/backend/domain/user/entity/User.java
  src/main/java/com/moayo/moayoeats/backend/domain/user/service/UserService.java
  src/main/java/com/moayo/moayoeats/backend/domain/user/service/impl/UserServiceImpl.java
Labels: feature

#233 Feat/user pw update
  src/main/java/com/moayo/moayoeats/backend/domain/user/controller/UserController.java
  src/main/java/com/moayo/moayoeats/backend/domain/user/dto/request/PasswordUpdateRequest.java
  src/main/java/com/moayo/moayoeats/backend/domain/user/entity/User.java
  src/main/java/com/moayo/moayoeats/backend/domain/user/service/UserService.java
  src/main/java/com/moayo/moayoeats/backend/domain/user/service/impl/UserServiceImpl.java
Labels: feature

#242 Feat/detailed post page
  src/main/java/com/moayo/moayoeats/backend/domain/post/controller/PostController.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/dto/response/DetailedPostResponse.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/service/PostService.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/service/impl/PostServiceImpl.java
  src/main/java/com/moayo/moayoeats/frontend/domain/post/PostFrontController.java
  src/main/resources/templates/domain/post/readpost.html
Labels: feature

#243 Feat/login front
  src/main/java/com/moayo/moayoeats/backend/global/config/WebSecurityConfig.java
  src/main/java/com/moayo/moayoeats/frontend/domain/user/UserFrontController.java
  src/main/resources/templates/domain/user/login.html
Labels: feature

#255 Feat/event from post #136
  src/main/java/com/moayo/moayoeats/backend/domain/post/service/impl/PostServiceImpl.java
Labels: feature

#256 Feat/review and score
  src/main/java/com/moayo/moayoeats/backend/domain/order/exception/OrderErrorCode.java
  src/main/java/com/moayo/moayoeats/backend/domain/order/repository/OrderRepository.java
  src/main/java/com/moayo/moayoeats/backend/domain/review/controller/ReviewController.java
  src/main/java/com/moayo/moayoeats/backend/domain/review/dto/request/ReviewRequest.java
  src/main/java/com/moayo/moayoeats/backend/domain/review/entity/Review.java
  src/main/java/com/moayo/moayoeats/backend/domain/review/entity/ScoreEnum.java
  src/main/java/com/moayo/moayoeats/backend/domain/review/repository/ReviewRepository.java
  src/main/java/com/moayo/moayoeats/backend/domain/review/service/ReviewService.java
  src/main/java/com/moayo/moayoeats/backend/domain/review/service/impl/ReviewServiceImpl.java
  src/main/java/com/moayo/moayoeats/backend/domain/user/repository/UserRepository.java
Labels: feature

#258 Feat/open my page
  src/main/java/com/moayo/moayoeats/backend/domain/user/controller/UserController.java
  src/main/java/com/moayo/moayoeats/backend/domain/user/dto/response/MyPageResponse.java
  src/main/java/com/moayo/moayoeats/backend/domain/user/service/UserService.java
  src/main/java/com/moayo/moayoeats/backend/domain/user/service/impl/UserServiceImpl.java
Labels: feature

#261 Feat/chat mongodb
  build.gradle
  src/main/java/com/moayo/moayoeats/MoayoeatsApplication.java
  src/main/java/com/moayo/moayoeats/backend/domain/chat/controlloer/ChatController.java
  src/main/java/com/moayo/moayoeats/backend/domain/chat/dto/ChatMessage.java
  src/main/java/com/moayo/moayoeats/backend/domain/chat/dto/ChatMessageDTO.java
  src/main/java/com/moayo/moayoeats/backend/domain/chat/entity/ChatMessage.java
  src/main/java/com/moayo/moayoeats/backend/domain/chat/repository/ChatMessageRepository.java
  src/main/java/com/moayo/moayoeats/backend/domain/chat/service/ChatMessageService.java
  src/main/java/com/moayo/moayoeats/backend/domain/chat/service/impl/ChatMessageServiceImpl.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/service/impl/PostServiceImpl.java
Labels: feature

#269 Feat/post create front #9
  src/main/java/com/moayo/moayoeats/backend/domain/post/dto/request/PostRequest.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/service/impl/PostServiceImpl.java
  src/main/java/com/moayo/moayoeats/frontend/domain/post/PostFrontController.java
  src/main/resources/templates/domain/post/createpost.html
Labels: style, feature, design

#277 Feat/refactor close
  src/main/java/com/moayo/moayoeats/backend/domain/post/exception/PostErrorCode.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/service/impl/PostServiceImpl.java
Labels: ⛏️refactor, feature

#278 Feat/signup front
  src/main/java/com/moayo/moayoeats/backend/global/config/WebSecurityConfig.java
  src/main/java/com/moayo/moayoeats/frontend/domain/user/UserFrontController.java
  src/main/resources/templates/domain/user/login.html
  src/main/resources/templates/domain/user/signup.html
Labels: feature

#268 Feat/get reviews and score
  src/main/java/com/moayo/moayoeats/backend/domain/review/controller/ReviewController.java
  src/main/java/com/moayo/moayoeats/backend/domain/review/dto/response/ReviewResponse.java
  src/main/java/com/moayo/moayoeats/backend/domain/review/service/ReviewService.java
  src/main/java/com/moayo/moayoeats/backend/domain/review/service/impl/ReviewServiceImpl.java
Labels: feature

#272 Feat/event from menu #136
  src/main/java/com/moayo/moayoeats/backend/domain/menu/service/impl/MenuServiceImpl.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/entity/Post.java
Labels: feature

#282 Feat/open my page
  src/main/java/com/moayo/moayoeats/backend/domain/user/dto/response/MyPageResponse.java
  src/main/java/com/moayo/moayoeats/backend/domain/user/service/impl/UserServiceImpl.java
Labels: feature

#284 Refactor/notification
  src/main/java/com/moayo/moayoeats/backend/domain/notification/entity/Notification.java
  src/main/java/com/moayo/moayoeats/backend/domain/notification/event/Event.java
  src/main/java/com/moayo/moayoeats/backend/domain/notification/event/NotificationListener.java
  src/main/java/com/moayo/moayoeats/backend/domain/notification/repository/NotificationRepository.java
  src/main/java/com/moayo/moayoeats/backend/domain/notification/service/impl/NotificationServiceImpl.java
Labels: ⛏️refactor

#285 Feat/open other user page
  src/main/java/com/moayo/moayoeats/backend/domain/user/controller/UserController.java
  src/main/java/com/moayo/moayoeats/backend/domain/user/dto/response/OtherUserPageResponse.java
  src/main/java/com/moayo/moayoeats/backend/domain/user/service/UserService.java
  src/main/java/com/moayo/moayoeats/backend/domain/user/service/impl/UserServiceImpl.java
Labels: ⛏️refactor, feature

#291 Feat/cancel application
  src/main/java/com/moayo/moayoeats/backend/domain/post/controller/PostController.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/exception/PostErrorCode.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/service/impl/PostServiceImpl.java
Labels: ⛏️refactor, feature

#292 Feat/cannot exit when closed
  src/main/java/com/moayo/moayoeats/backend/domain/post/exception/PostErrorCode.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/service/impl/PostServiceImpl.java
Labels: ⛏️refactor, feature

#300 Feat/read all posts page
  src/main/java/com/moayo/moayoeats/backend/domain/post/controller/PostController.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/service/PostService.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/service/impl/PostServiceImpl.java
  src/main/java/com/moayo/moayoeats/backend/global/config/WebSecurityConfig.java
  src/main/java/com/moayo/moayoeats/frontend/domain/post/PostFrontController.java
  src/main/resources/templates/domain/post/allposts.html
Labels: feature

#303 Feat/scheduler
  build.gradle
  src/main/java/com/moayo/moayoeats/MoayoeatsApplication.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/service/impl/PostServiceImpl.java
Labels: feature

#305 Feat/front mypage
  src/main/java/com/moayo/moayoeats/backend/domain/user/controller/UserController.java
  src/main/java/com/moayo/moayoeats/backend/global/jwt/JwtUtil.java
  src/main/java/com/moayo/moayoeats/backend/global/security/JwtAuthorizationFilter.java
  src/main/java/com/moayo/moayoeats/frontend/domain/user/UserFrontController.java
  src/main/resources/static/js/basic.js
  src/main/resources/templates/domain/user/login.html
  src/main/resources/templates/domain/user/mypage.html
Labels: fix

#307 fix: 다른 페이지로 Authorization 전달되게 함
  src/main/resources/templates/domain/user/login.html
Labels: fix

#306 Feat/delete offers when close
  src/main/java/com/moayo/moayoeats/backend/domain/post/service/impl/PostServiceImpl.java
  src/main/java/com/moayo/moayoeats/backend/global/config/WebSecurityConfig.java
Labels: feature

#308 fix: 토큰 관련 문제 수정
  src/main/java/com/moayo/moayoeats/backend/domain/user/controller/UserController.java
  src/main/java/com/moayo/moayoeats/backend/global/security/JwtAuthorizationFilter.java
Labels: fix

#313 Feat/not delete menus when delete post
  src/main/java/com/moayo/moayoeats/backend/domain/menu/entity/Menu.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/entity/Post.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/service/impl/PostServiceImpl.java
Labels: ⛏️refactor, feature

#317 Feat/remove test methods
  src/main/java/com/moayo/moayoeats/backend/domain/post/controller/PostController.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/service/PostService.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/service/impl/PostServiceImpl.java
  src/main/java/com/moayo/moayoeats/frontend/domain/post/PostFrontController.java
  src/main/resources/templates/domain/post/createpost.html
Labels: ⛏️refactor

#319 fix: login, mypage에 header, navbar 위치경로 수정
  src/main/resources/templates/domain/user/login.html
  src/main/resources/templates/domain/user/mypage.html
Labels: fix

#327 Feat/front mypage
  src/main/resources/static/js/basic.js
  src/main/resources/templates/domain/user/mypage.html
  src/main/resources/templates/global/navbar.html
Labels: feature

#336 Feat/front other user page
  src/main/java/com/moayo/moayoeats/frontend/domain/user/UserFrontController.java
  src/main/resources/templates/domain/user/other-user-page.html
Labels: feature

#332 Feat/post page
  src/main/java/com/moayo/moayoeats/backend/domain/post/dto/response/DetailedPostResponse.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/service/impl/PostServiceImpl.java
  src/main/java/com/moayo/moayoeats/frontend/domain/post/PostFrontController.java
  src/main/resources/templates/domain/post/post.html
Labels: ⛏️refactor, feature

#342 Feat/menu page
  src/main/java/com/moayo/moayoeats/backend/domain/menu/controller/MenuController.java
  src/main/java/com/moayo/moayoeats/backend/domain/menu/dto/response/MenuResponse.java
  src/main/java/com/moayo/moayoeats/backend/domain/menu/service/MenuService.java
  src/main/java/com/moayo/moayoeats/backend/domain/menu/service/impl/MenuServiceImpl.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/service/impl/PostServiceImpl.java
  src/main/java/com/moayo/moayoeats/backend/domain/review/service/impl/ReviewServiceImpl.java
  src/main/java/com/moayo/moayoeats/frontend/domain/menu/MenuFrontController.java
  src/main/resources/templates/domain/menu/menu.html
  src/main/resources/templates/domain/post/post.html
Labels: feature

#350 Feat/token expiration related
  src/main/java/com/moayo/moayoeats/backend/global/config/WebSecurityConfig.java
  src/main/java/com/moayo/moayoeats/backend/global/jwt/JwtUtil.java
  src/main/java/com/moayo/moayoeats/backend/global/security/JwtAuthenticationEntryPoint.java
  src/main/resources/static/js/basic.js
  src/main/resources/templates/domain/user/login.html
  src/main/resources/templates/domain/user/mypage.html
Labels: ⛏️refactor, feature

#354 refactor: 채팅db에 userId 추가 및 수정
  src/main/java/com/moayo/moayoeats/backend/domain/chat/controlloer/ChatController.java
  src/main/java/com/moayo/moayoeats/backend/domain/chat/dto/ChatMessageDTO.java
  src/main/java/com/moayo/moayoeats/backend/domain/chat/entity/ChatMessage.java
  src/main/java/com/moayo/moayoeats/backend/domain/chat/service/ChatMessageService.java
  src/main/java/com/moayo/moayoeats/backend/domain/chat/service/impl/ChatMessageServiceImpl.java
Labels: ⛏️refactor

#358 Feat/front update nickname
  src/main/java/com/moayo/moayoeats/frontend/domain/user/UserFrontController.java
  src/main/resources/templates/domain/user/mypage.html
  src/main/resources/templates/domain/user/update-nickname.html
Labels: feature, design

#369 Feat/review page
  src/main/java/com/moayo/moayoeats/backend/domain/review/dto/request/ReviewRequest.java
  src/main/java/com/moayo/moayoeats/backend/domain/review/service/impl/ReviewServiceImpl.java
  src/main/java/com/moayo/moayoeats/frontend/domain/review/ReviewFrontController.java
  src/main/resources/templates/domain/review/createreview.html
Labels: feature

#372 Feat/all posts page
  src/main/java/com/moayo/moayoeats/backend/domain/post/controller/PostController.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/exception/validator/Category.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/repository/PostRepository.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/service/PostService.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/service/impl/PostServiceImpl.java
  src/main/java/com/moayo/moayoeats/frontend/domain/post/PostFrontController.java
  src/main/resources/templates/domain/post/posts.html
Labels: ⛏️refactor, feature

#377 Feat/paging post
  src/main/java/com/moayo/moayoeats/backend/domain/post/controller/PostController.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/service/PostService.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/service/impl/PostServiceImpl.java
Labels: ⛏️refactor

#370 Feat/front update pw
  src/main/java/com/moayo/moayoeats/frontend/domain/user/UserFrontController.java
  src/main/resources/templates/domain/user/mypage.html
  src/main/resources/templates/domain/user/update-password.html
Labels: feature

#384 Feat/update address
  src/main/java/com/moayo/moayoeats/backend/domain/user/controller/UserController.java
  src/main/java/com/moayo/moayoeats/backend/domain/user/dto/request/AddressUpdateRequest.java
  src/main/java/com/moayo/moayoeats/backend/domain/user/entity/User.java
  src/main/java/com/moayo/moayoeats/backend/domain/user/service/UserService.java
  src/main/java/com/moayo/moayoeats/backend/domain/user/service/impl/UserServiceImpl.java
Labels: feature

#383 fix: 중복되는 url path 수정
  src/main/java/com/moayo/moayoeats/backend/domain/post/controller/PostController.java
Labels: fix

#351 chore : 자동배포 관련 파일 수정 #320
  .github/workflows/check.yml
  .github/workflows/deploy.yml
  .github/workflows/main.yml
  appspec.yml
  build.gradle
  deploy.sh
  env
  src/main/resources/application.yml
  src/main/resources/static/index.html
Labels: chore

#394 Feat/category paging
  src/main/java/com/moayo/moayoeats/backend/domain/post/controller/PostController.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/repository/PostRepository.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/service/PostService.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/service/impl/PostServiceImpl.java
Labels: feature

#402 Feat/search paging
  src/main/java/com/moayo/moayoeats/backend/domain/post/controller/PostController.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/repository/PostRepository.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/service/PostService.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/service/impl/PostServiceImpl.java
Labels: feature

#403 style: 로그인 css
  src/main/resources/templates/domain/user/login.html
Labels: design

#404 Refactor/cicd
  .github/workflows/check.yml
Labels: ⛏️refactor

#405 feat : mypage와 createreview페이지 연결
  src/main/resources/templates/domain/user/mypage.html
Labels: feature

#410 Feat/chatroom front
  src/main/java/com/moayo/moayoeats/backend/domain/chat/controlloer/ChatController.java
  src/main/java/com/moayo/moayoeats/backend/domain/chat/dto/ChatMessageDTO.java
  src/main/java/com/moayo/moayoeats/backend/domain/chat/dto/request/ChatMessageRequest.java
  src/main/java/com/moayo/moayoeats/backend/domain/chat/dto/response/ChatMessageResponse.java
  src/main/java/com/moayo/moayoeats/backend/domain/chat/entity/ChatMessage.java
  src/main/java/com/moayo/moayoeats/backend/domain/chat/service/ChatMessageService.java
  src/main/java/com/moayo/moayoeats/backend/domain/chat/service/impl/ChatMessageServiceImpl.java
  src/main/java/com/moayo/moayoeats/backend/domain/user/repository/UserRepository.java
  src/main/java/com/moayo/moayoeats/backend/global/config/WebSocketConfig.java
  src/main/resources/static/js/chat.js
  src/main/resources/templates/domain/chat/chatroom.html
Labels: ⛏️refactor, chore, feature, fix, design

#409 Feat/all posts page paging buttons
  src/main/resources/templates/domain/post/allposts.html
  src/main/resources/templates/domain/post/posts.html
Labels: ⛏️refactor

#411 Refactor/cicd !HOT!
  .github/workflows/check.yml
  .github/workflows/deploy.yml
  deploy.sh
  src/main/resources/application.yml
  src/main/resources/templates/index.html
  src/test/java/com/moayo/moayoeats/MoayoeatsApplicationTests.java
Labels: chore

#413 Feat/set map to their location
  src/main/java/com/moayo/moayoeats/backend/domain/user/controller/UserController.java
  src/main/java/com/moayo/moayoeats/backend/domain/user/dto/response/AddressResponse.java
  src/main/java/com/moayo/moayoeats/backend/domain/user/service/UserService.java
  src/main/java/com/moayo/moayoeats/backend/domain/user/service/impl/UserServiceImpl.java
  src/main/resources/templates/domain/post/createpost.html
Labels: ⛏️refactor, feature

#415 feat: posts 페이지에 글 작성하기 버튼 달기 #414
  src/main/resources/templates/domain/post/posts.html
Labels: feature

#420 refactor: 알림 조회시 내용관련 수정
  src/main/java/com/moayo/moayoeats/backend/domain/notification/dto/response/NotificationsResponse.java
Labels: ⛏️refactor

#424 refactor: post service에서의 event 추가
  src/main/java/com/moayo/moayoeats/backend/domain/notification/entity/NotificationType.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/service/impl/PostServiceImpl.java
Labels: feature

#427 feat: index.html로 요청이 들어갈때 로그인 상태/비로그인 상태 구분해서 html 호출 #422
  src/main/java/com/moayo/moayoeats/backend/global/security/JwtAuthorizationFilter.java
Labels: feature

#429 Feat/notification page
  src/main/java/com/moayo/moayoeats/backend/domain/notification/dto/response/NotificationsResponse.java
  src/main/java/com/moayo/moayoeats/frontend/domain/notification/NotificationFrontController.java
  src/main/resources/templates/domain/notification/notification.html
Labels: feature

#430 Feat/redirect
  src/main/resources/templates/domain/menu/menu.html
  src/main/resources/templates/domain/post/createpost.html
  src/main/resources/templates/domain/post/posts.html
  src/main/resources/templates/domain/review/createreview.html
Labels: feature

#425 refactor: event 로직 수정
  src/main/java/com/moayo/moayoeats/backend/domain/menu/service/impl/MenuServiceImpl.java
Labels: ⛏️refactor

#432 Feat/receive order after completed
  src/main/java/com/moayo/moayoeats/backend/domain/post/exception/PostErrorCode.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/service/impl/PostServiceImpl.java
Labels: feature

#421 Feat/chatroom
  src/main/java/com/moayo/moayoeats/backend/domain/chat/entity/ChatRoom.java
  src/main/java/com/moayo/moayoeats/backend/global/config/WebSocketConfig.java
Labels: ⛏️refactor, feature

#412 Fix/view offer
  src/main/java/com/moayo/moayoeats/backend/domain/menu/dto/response/NickMenusResponse.java
  src/main/java/com/moayo/moayoeats/backend/domain/menu/repository/MenuRepository.java
  src/main/java/com/moayo/moayoeats/backend/domain/offer/controller/OfferController.java
  src/main/java/com/moayo/moayoeats/backend/domain/offer/service/OfferService.java
  src/main/java/com/moayo/moayoeats/backend/domain/offer/service/impl/OfferServiceImpl.java
Labels: feature, fix

#437 chore: CD 테스트
  .github/workflows/deploy.yml
Labels: chore, fix

#434 Feat/notification icon
  src/main/resources/static/images/bell.png
  src/main/resources/templates/global/navbar.html
Labels: feature

#438 Feat/offer front page
  src/main/java/com/moayo/moayoeats/backend/domain/offer/controller/OfferController.java
  src/main/java/com/moayo/moayoeats/backend/domain/offer/dto/response/OfferRoleResponse.java
  src/main/java/com/moayo/moayoeats/backend/domain/offer/service/OfferService.java
  src/main/java/com/moayo/moayoeats/backend/domain/offer/service/impl/OfferServiceImpl.java
  src/main/java/com/moayo/moayoeats/backend/domain/userpost/repository/UserPostRepository.java
  src/main/resources/templates/domain/offer/get-offer.html
Labels: ⛏️refactor, feature

#439 fix: login, signup 필터단에서 허용
  .github/workflows/deploy.yml
  src/main/java/com/moayo/moayoeats/backend/global/config/WebSecurityConfig.java
  src/main/java/com/moayo/moayoeats/backend/global/security/JwtAuthorizationFilter.java
Labels: !HOTFIX

#440 fix: path 수정
  src/main/java/com/moayo/moayoeats/frontend/domain/post/PostFrontController.java
Labels: feature

#444 fix: offer 프론트 수정
  src/main/resources/templates/domain/offer/get-offer.html
Labels: !HOTFIX, fix

#443 fix: thymeleaf코드 모두 제거
  src/main/resources/templates/domain/post/allposts.html
  src/main/resources/templates/domain/post/createpost.html
  src/main/resources/templates/domain/post/post.html
  src/main/resources/templates/domain/post/posts.html
  src/main/resources/templates/domain/post/readpost.html
Labels: !HOTFIX, fix

#445 fix: cd test HOTFIX
  src/main/resources/templates/domain/chat/chatroom.html
  src/main/resources/templates/domain/menu/menu.html
  src/main/resources/templates/domain/notification/notification.html
  src/main/resources/templates/domain/review/createreview.html
  src/main/resources/templates/domain/user/login.html
  src/main/resources/templates/domain/user/mypage.html
  src/main/resources/templates/domain/user/other-user-page.html
  src/main/resources/templates/domain/user/update-address.html
  src/main/resources/templates/domain/user/update-nickname.html
  src/main/resources/templates/domain/user/update-password.html
Labels: !HOTFIX, fix

#447 refactor: 부트스트랩 다시 달아봄
  src/main/resources/templates/domain/post/readpost.html
  src/main/resources/templates/index.html
Labels: ⛏️refactor

#448 refactor: setAllowedOrigins 수정
  src/main/java/com/moayo/moayoeats/backend/global/config/WebSocketConfig.java
  src/main/java/com/moayo/moayoeats/frontend/domain/chat/ChatFrontController.java
  src/main/resources/templates/domain/chat/chatroom.html
Labels: ⛏️refactor

#450 Feat/login button
  src/main/resources/static/images/login.png
  src/main/resources/static/images/signup.png
  src/main/resources/static/images/user.png
  src/main/resources/templates/domain/menu/menu.html
  src/main/resources/templates/domain/notification/notification.html
  src/main/resources/templates/domain/offer/get-offer.html
  src/main/resources/templates/domain/post/allposts.html
  src/main/resources/templates/domain/post/createpost.html
  src/main/resources/templates/domain/post/post.html
  src/main/resources/templates/domain/post/posts.html
  src/main/resources/templates/domain/post/readpost.html
  src/main/resources/templates/domain/review/createreview.html
  src/main/resources/templates/index.html
Labels: feature

#449 fix: 지도 api 다시 달아봄
  src/main/resources/templates/domain/post/readpost.html
Labels: fix

#451 chore: mongodb atlas
  src/main/resources/application.yml
Labels: chore, feature

#452 Style/navbar
  src/main/resources/static/css/navbar.css
  src/main/resources/static/js/navbar.js
  src/main/resources/templates/domain/user/mypage.html
Labels: design

#454 fix: cd test HOTFIX
  src/main/resources/application.yml
Labels: !HOTFIX, fix

#456 Style/post
  src/main/resources/static/css/index.css
  src/main/resources/static/js/navbar.js
  src/main/resources/templates/domain/post/posts.html
  src/main/resources/templates/index.html
Labels: design

#459 Feat/put mypage to offer nickname
  src/main/java/com/moayo/moayoeats/backend/domain/offer/dto/response/OfferResponse.java
  src/main/java/com/moayo/moayoeats/backend/domain/offer/service/impl/OfferServiceImpl.java
  src/main/resources/templates/domain/offer/get-offer.html
Labels: feature

#455 fix: 채팅 메시지 저장 임시 주석 처리
  src/main/java/com/moayo/moayoeats/backend/domain/chat/controlloer/ChatController.java
  src/main/java/com/moayo/moayoeats/backend/domain/chat/service/ChatMessageService.java
  src/main/resources/application.yml
  src/main/resources/templates/domain/post/post.html
Labels: fix

#461 feat: PostService 코드 다소 정리
  src/main/java/com/moayo/moayoeats/backend/domain/post/controller/PostController.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/service/PostService.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/service/impl/PostServiceImpl.java
Labels: ⛏️refactor

#462 Feat/auth exception
  src/main/java/com/moayo/moayoeats/backend/global/config/WebSecurityConfig.java
  src/main/java/com/moayo/moayoeats/backend/global/jwt/JwtUtil.java
  src/main/java/com/moayo/moayoeats/backend/global/security/JwtAccessDeniedHandler.java
  src/main/java/com/moayo/moayoeats/backend/global/security/JwtAuthenticationEntryPoint.java
  src/main/java/com/moayo/moayoeats/backend/global/security/JwtAuthorizationFilter.java
  src/main/resources/static/js/basic.js
  src/main/resources/static/js/navbar.js
  src/main/resources/templates/domain/user/login.html
  src/main/resources/templates/domain/user/mypage.html
Labels: feature

#463 Style/detail view post
  src/main/resources/application.yml
  src/main/resources/static/css/readpost.css
  src/main/resources/templates/domain/post/createpost.html
  src/main/resources/templates/domain/post/post.html
  src/main/resources/templates/domain/post/readpost.html
  src/main/resources/templates/index.html
Labels: fix, design

#466 Feat/sorting desc
  src/main/java/com/moayo/moayoeats/backend/domain/post/entity/Post.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/repository/PostRepository.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/service/impl/PostServiceImpl.java
Labels: ⛏️refactor

#471 style: 회원가입 창에서 비밀번호 input창 클릭시 비밀번호 형식 안내
  src/main/resources/templates/domain/user/signup.html
Labels: design

#472 feat/signup
  src/main/java/com/moayo/moayoeats/backend/domain/user/exception/UserErrorCode.java
  src/main/java/com/moayo/moayoeats/backend/domain/user/repository/UserRepository.java
  src/main/java/com/moayo/moayoeats/backend/domain/user/service/impl/UserServiceImpl.java
  src/main/resources/templates/domain/user/signup.html
Labels: feature, fix

#477 Feat/display post status
  src/main/java/com/moayo/moayoeats/backend/domain/menu/service/impl/MenuServiceImpl.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/dto/response/BriefPostResponse.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/exception/PostErrorCode.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/service/impl/PostServiceImpl.java
  src/main/resources/templates/domain/post/post.html
  src/main/resources/templates/domain/post/posts.html
  src/main/resources/templates/index.html
Labels: ⛏️refactor

#480 Feat/add navbar
  src/main/resources/templates/domain/chat/chatroom.html
  src/main/resources/templates/domain/menu/menu.html
  src/main/resources/templates/domain/notification/notification.html
  src/main/resources/templates/domain/offer/get-offer.html
  src/main/resources/templates/domain/post/allposts.html
  src/main/resources/templates/domain/post/createpost.html
  src/main/resources/templates/domain/review/createreview.html
  src/main/resources/templates/domain/user/update-address.html
  src/main/resources/templates/domain/user/update-nickname.html
  src/main/resources/templates/domain/user/update-password.html
Labels: feature

#479 Feat/back to post page button
  src/main/resources/templates/domain/menu/menu.html
  src/main/resources/templates/domain/post/posts.html
Labels: ⛏️refactor

#486 Feat/auth alert
  src/main/java/com/moayo/moayoeats/backend/global/jwt/JwtUtil.java
  src/main/resources/static/js/basic.js
  src/main/resources/templates/domain/notification/notification.html
  src/main/resources/templates/domain/post/allposts.html
  src/main/resources/templates/domain/post/createpost.html
  src/main/resources/templates/domain/post/posts.html
  src/main/resources/templates/domain/post/readpost.html
  src/main/resources/templates/domain/user/login.html
  src/main/resources/templates/domain/user/mypage.html
  src/main/resources/templates/index.html
Labels: feature, fix, design

#484 feat: 요청조회 페이지에서 글 페이지로 돌아가는 버튼 구현 #436
  src/main/resources/templates/domain/offer/get-offer.html
Labels: feature

#485 Feat/display remained time
  src/main/java/com/moayo/moayoeats/backend/domain/post/dto/response/DetailedPostResponse.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/service/impl/PostServiceImpl.java
  src/main/resources/templates/domain/post/post.html
  src/main/resources/templates/domain/post/readpost.html
Labels: ⛏️refactor

#488 Feat/fix time calculation
  src/main/java/com/moayo/moayoeats/backend/domain/post/service/impl/PostServiceImpl.java
Labels: ⛏️refactor

#489 Style/front update
  src/main/resources/static/css/login.css
  src/main/resources/static/css/signup.css
  src/main/resources/templates/domain/chat/chatroom.html
  src/main/resources/templates/domain/menu/menu.html
  src/main/resources/templates/domain/notification/notification.html
  src/main/resources/templates/domain/offer/get-offer.html
  src/main/resources/templates/domain/post/allposts.html
  src/main/resources/templates/domain/post/createpost.html
  src/main/resources/templates/domain/post/post.html
  src/main/resources/templates/domain/post/posts.html
  src/main/resources/templates/domain/post/readpost.html
  src/main/resources/templates/domain/review/createreview.html
  src/main/resources/templates/domain/user/login.html
  src/main/resources/templates/domain/user/mypage.html
  src/main/resources/templates/domain/user/other-user-page.html
  src/main/resources/templates/domain/user/signup.html
  src/main/resources/templates/domain/user/update-address.html
  src/main/resources/templates/domain/user/update-nickname.html
  src/main/resources/templates/domain/user/update-password.html
  src/main/resources/templates/index.html
Labels: ⛏️refactor, feature, design

#497 Feat/refactor chat
  src/main/java/com/moayo/moayoeats/backend/domain/chat/controlloer/ChatController.java
  src/main/java/com/moayo/moayoeats/backend/domain/chat/dto/response/ChatMessageResponse.java
  src/main/java/com/moayo/moayoeats/backend/domain/chat/repository/ChatMessageRepository.java
  src/main/java/com/moayo/moayoeats/backend/domain/chat/service/impl/ChatMessageServiceImpl.java
  src/main/resources/static/css/style.css
  src/main/resources/static/js/chat.js
  src/main/resources/templates/domain/chat/chatroom.html
Labels: ⛏️refactor, feature, design

#490 fix: 닉네임 수정시 닉네임 중복 체크
  src/main/java/com/moayo/moayoeats/backend/domain/user/service/impl/UserServiceImpl.java
Labels: fix

#491 Feat/redirect after approving or rejecting an offer
  src/main/resources/templates/domain/offer/get-offer.html
Labels: ⛏️refactor

#499 feat: 로그인 후 인증정보없는 글 상세페이지로 가면 로그인 후 상세페이지로 redirect #498
  src/main/java/com/moayo/moayoeats/backend/global/security/JwtAuthorizationFilter.java
Labels: feature

#502 refactor: 글 나가기 기능 refactor
  src/main/java/com/moayo/moayoeats/backend/domain/post/exception/PostErrorCode.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/service/PostService.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/service/impl/PostServiceImpl.java
Labels: ⛏️refactor

#503 Fix/change about pw for ut
  src/main/java/com/moayo/moayoeats/backend/domain/user/dto/request/SignupRequest.java
  src/main/resources/templates/domain/user/signup.html
Labels: fix

#505 Feat/fix front button
  src/main/resources/templates/domain/post/post.html
Labels: ⛏️refactor, fix

#501 feat: 메시지 전송 시간 추가
  src/main/java/com/moayo/moayoeats/backend/domain/chat/controlloer/ChatController.java
  src/main/java/com/moayo/moayoeats/backend/domain/chat/dto/response/ChatMessageResponse.java
  src/main/java/com/moayo/moayoeats/backend/domain/chat/service/ChatMessageService.java
  src/main/java/com/moayo/moayoeats/backend/domain/chat/service/impl/ChatMessageServiceImpl.java
  src/main/java/com/moayo/moayoeats/backend/global/config/WebSocketConfig.java
  src/main/resources/static/css/style.css
  src/main/resources/static/js/chat.js
Labels: ⛏️refactor, feature, design

#508 designCSS: font
  src/main/resources/static/css/fonts.css
  src/main/resources/static/index-temp.html
  src/main/resources/templates/domain/menu/menu.html
  src/main/resources/templates/domain/notification/notification.html
  src/main/resources/templates/domain/offer/get-offer.html
  src/main/resources/templates/domain/post/allposts.html
  src/main/resources/templates/domain/post/createpost.html
  src/main/resources/templates/domain/post/post.html
  src/main/resources/templates/domain/post/posts.html
  src/main/resources/templates/domain/post/readpost.html
  src/main/resources/templates/domain/review/createreview.html
  src/main/resources/templates/domain/user/login.html
  src/main/resources/templates/domain/user/mypage.html
  src/main/resources/templates/domain/user/other-user-page.html
  src/main/resources/templates/domain/user/signup.html
  src/main/resources/templates/domain/user/update-address.html
  src/main/resources/templates/domain/user/update-nickname.html
  src/main/resources/templates/domain/user/update-password.html
  src/main/resources/templates/index.html
Labels: design

#510 Fix/order
  src/main/java/com/moayo/moayoeats/backend/domain/post/controller/PostController.java
  src/main/resources/templates/domain/post/post.html
  src/main/resources/templates/domain/user/mypage.html
Labels: fix

#507 refactor: 주석 수정
  src/main/java/com/moayo/moayoeats/backend/domain/post/controller/PostController.java
Labels: ⛏️refactor

#511 Feat/not delete post after received
  src/main/java/com/moayo/moayoeats/backend/domain/post/service/impl/PostServiceImpl.java
Labels: ⛏️refactor

#514 refactor: 모집중인 상태가 아니면 마감시간이 출력되지 않도록 함
  src/main/resources/templates/index.html
Labels: ⛏️refactor

#515 Chore/docker process v0.2.01 #458
  .github/workflows/check.yml
  .github/workflows/deploy-docker-v0.2.01.yml
  .github/workflows/deploy.yml
  infra/Dockerfile
Labels: chore

#516 Feat/refactor validation
  src/main/java/com/moayo/moayoeats/backend/domain/post/dto/request/PostRequest.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/exception/validator/Hours.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/exception/validator/HoursValidator.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/exception/validator/Minutes.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/exception/validator/MinutesValidator.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/exception/validator/Money.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/exception/validator/MoneyValidator.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/service/impl/PostServiceImpl.java
  src/main/resources/templates/domain/post/createpost.html
Labels: ⛏️refactor, feature

#517 feat: post.html에서 버튼 누른 후 페이지 리다이렉트 #513
  src/main/resources/templates/domain/post/post.html
Labels: ⛏️refactor, feature

#528 feat: 거리별 정렬 QueryDsl 메서드 refactor #527
  src/main/java/com/moayo/moayoeats/backend/domain/post/repository/PostCustomRepositoryImpl.java
Labels: ⛏️refactor, feature

#529 Feat/sorting by distance and category
  src/main/java/com/moayo/moayoeats/backend/domain/post/repository/PostCustomRepository.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/repository/PostCustomRepositoryImpl.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/service/impl/PostServiceImpl.java
Labels: ⛏️refactor

#531 Feat/sorting by distance and keyword
  src/main/java/com/moayo/moayoeats/backend/domain/post/repository/PostCustomRepository.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/repository/PostCustomRepositoryImpl.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/service/impl/PostServiceImpl.java
Labels: ⛏️refactor, feature
