Repository moayoeats/moayoeats, pull requests merged in 2024-02, with the labels that each got.

#506 fix: 마이페이지 연결 관련 문제 해결
  src/main/resources/static/js/chat.js
Labels: fix

#532 Feat/refactor chatroom
  src/main/java/com/moayo/moayoeats/backend/global/config/WebSocketConfig.java
  src/main/resources/static/js/chat.js
Labels: ⛏️refactor

#553 Feat/refresh token
  build.gradle
  src/main/java/com/moayo/moayoeats/backend/domain/user/controller/UserController.java
  src/main/java/com/moayo/moayoeats/backend/domain/user/dto/response/LoginResponse.java
  src/main/java/com/moayo/moayoeats/backend/domain/user/service/UserService.java
  src/main/java/com/moayo/moayoeats/backend/domain/user/service/impl/UserServiceImpl.java
  src/main/java/com/moayo/moayoeats/backend/global/config/RedisConfig.java
  src/main/java/com/moayo/moayoeats/backend/global/config/WebSecurityConfig.java
  src/main/java/com/moayo/moayoeats/backend/global/jwt/JwtUtil.java
  src/main/java/com/moayo/moayoeats/backend/global/jwt/TokenService.java
  src/main/java/com/moayo/moayoeats/backend/global/security/JwtAuthorizationFilter.java
  src/main/resources/application.yml
  src/main/resources/static/js/basic.js
  src/main/resources/templates/domain/notification/notification.html
  src/main/resources/templates/domain/post/posts.html
  src/main/resources/templates/domain/user/login.html
  src/main/resources/templates/domain/user/mypage.html
Labels: ⛏️refactor, feature, fix

#526 Feat/push notification 배포 테스트
  src/main/java/com/moayo/moayoeats/backend/domain/offer/service/impl/OfferServiceImpl.java
  src/main/java/com/moayo/moayoeats/backend/domain/pushEvent/EmitterRepository.java
  src/main/java/com/moayo/moayoeats/backend/domain/pushEvent/PushEventController.java
  src/main/java/com/moayo/moayoeats/backend/domain/pushEvent/PushEventService.java
  src/main/java/com/moayo/moayoeats/backend/domain/pushEvent/dto/PushEventDto.java
  src/main/java/com/moayo/moayoeats/backend/domain/pushEvent/exception/PushEventErrorCode.java
  src/main/java/com/moayo/moayoeats/backend/domain/pushEvent/repository/EmitterRepositoryImpl.java
  src/main/java/com/moayo/moayoeats/frontend/domain/offer/OfferFrontController.java
  src/main/java/com/moayo/moayoeats/frontend/domain/post/PostFrontController.java
  src/main/resources/static/js/sse.js
  src/main/resources/templates/domain/offer/get-offer.html
  src/main/resources/templates/domain/post/post.html
  src/main/resources/templates/domain/post/posts.html
Labels: feature

#555 fix: index.html 의 글 출력 메서드 수정
  src/main/resources/templates/index.html
Labels: fix

#554 chore: CD 과정 도커로 변경
  .github/workflows/deploy.yml
Labels: chore

#556 Feat/sorting posts by status and category
  src/main/java/com/moayo/moayoeats/backend/domain/post/controller/PostController.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/exception/validator/PostStatus.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/exception/validator/PostStatusValidator.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/repository/PostCustomRepository.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/repository/PostCustomRepositoryImpl.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/service/PostService.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/service/impl/PostServiceImpl.java
  src/main/resources/templates/domain/post/posts.html
Labels: ⛏️refactor, feature

#557 fix: 주소 변경 안되는 문제 해결
  src/main/resources/static/js/basic.js
Labels: fix

#558 Chore/docker 파일 필요없는 부분 수정
  .github/workflows/deploy-docker-v0.2.01.yml
  .github/workflows/deploy.yml
Labels: chore, !HOTFIX, fix

#559 fix: received 상태로 변경 후 저장하지 않던 문제 수정
  src/main/java/com/moayo/moayoeats/backend/domain/post/service/impl/PostServiceImpl.java
Labels: fix

#560 Feat/sorting posts by status and category
  src/main/java/com/moayo/moayoeats/backend/domain/post/controller/PostController.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/repository/PostCustomRepository.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/repository/PostCustomRepositoryImpl.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/service/PostService.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/service/impl/PostServiceImpl.java
  src/main/resources/static/js/posts.js
  src/main/resources/templates/domain/post/posts.html
Labels: feature

#562 chore: 배포 테스트
  .github/workflows/deploy.yml
Labels: chore, !HOTFIX, fix

#563 chor: 배포 테스트
  .github/workflows/deploy.yml
  .gitignore
Labels: chore, !HOTFIX, fix

#564 Chore/deploy
  .github/workflows/deploy.yml
  .gitignore
Labels: chore, !HOTFIX, fix

#565 Feat/get posts by status and keyword
  src/main/java/com/moayo/moayoeats/backend/domain/post/controller/PostController.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/repository/PostCustomRepository.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/repository/PostCustomRepositoryImpl.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/service/PostService.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/service/impl/PostServiceImpl.java
  src/main/resources/static/js/posts.js
Labels: feature

#566 fix: 수령완료 후에 해당 User의 UserPost 삭제함
  src/main/java/com/moayo/moayoeats/backend/domain/post/service/impl/PostServiceImpl.java
Labels: fix

#567 Feat/push notification #522
  .github/workflows/deploy.yml
  src/main/java/com/moayo/moayoeats/backend/domain/menu/service/impl/MenuServiceImpl.java
  src/main/java/com/moayo/moayoeats/backend/domain/offer/controller/OfferController.java
  src/main/java/com/moayo/moayoeats/backend/domain/offer/service/impl/OfferServiceImpl.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/service/impl/PostServiceImpl.java
  src/main/java/com/moayo/moayoeats/backend/domain/pushEvent/PushEventService.java
  src/main/java/com/moayo/moayoeats/frontend/domain/menu/MenuFrontController.java
  src/main/java/com/moayo/moayoeats/frontend/domain/notification/NotificationFrontController.java
  src/main/java/com/moayo/moayoeats/frontend/domain/review/ReviewFrontController.java
  src/main/java/com/moayo/moayoeats/frontend/domain/user/UserFrontController.java
  src/main/resources/templates/domain/chat/chatroom.html
  src/main/resources/templates/domain/menu/menu.html
  src/main/resources/templates/domain/notification/notification.html
  src/main/resources/templates/domain/review/createreview.html
  src/main/resources/templates/domain/user/mypage.html
  src/main/resources/templates/domain/user/other-user-page.html
  src/main/resources/templates/domain/user/update-password.html
  src/main/resources/templates/index.html
Labels: feature

#569 Feat/add category cafe
  src/main/java/com/moayo/moayoeats/backend/domain/post/dto/request/PostRequest.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/entity/CategoryEnum.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/entity/Post.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/exception/validator/CategoryValidator.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/repository/PostCustomRepository.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/repository/PostCustomRepositoryImpl.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/repository/PostRepository.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/service/impl/PostServiceImpl.java
  src/main/resources/templates/domain/post/createpost.html
  src/main/resources/templates/domain/post/posts.html
  src/main/resources/templates/index.html
Labels: feature

#573 Feat/refactor chatroom
  src/main/java/com/moayo/moayoeats/frontend/domain/chat/ChatFrontController.java
  src/main/resources/static/js/chat.js
Labels: feature

#574 Fix/get all posts
  src/main/java/com/moayo/moayoeats/backend/domain/post/exception/validator/PostStatusValidator.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/service/impl/PostServiceImpl.java
  src/main/resources/static/js/posts.js
  src/main/resources/templates/domain/post/posts.html
Labels: ⛏️refactor, fix

#579 test: notificationServiceImpl
  src/test/java/com/moayo/moayoeats/backend/domain/notification/service/impl/NotificationServiceImplTest.java
Labels: test

#570 refactor: UT를 위해 쉽게 변경했던 password 조건 다시 변경
  src/main/java/com/moayo/moayoeats/backend/domain/user/dto/request/SignupRequest.java
Labels: ⛏️refactor

#584 Feat/separate create post service from post service
  src/main/java/com/moayo/moayoeats/backend/domain/post/controller/PostController.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/service/PostCreateService.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/service/PostService.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/service/impl/PostCreateServiceImpl.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/service/impl/PostServiceImpl.java
Labels: ⛏️refactor

#587 Feat/separate read post service from post service
  src/main/java/com/moayo/moayoeats/backend/domain/post/controller/PostController.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/repository/PostCustomRepository.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/repository/PostCustomRepositoryImpl.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/service/PostReadService.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/service/PostService.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/service/impl/PostReadServiceImpl.java
  src/main/java/com/moayo/moayoeats/backend/domain/post/service/impl/PostServiceImpl.java
Labels: ⛏️refactor

#585 Test/user test code
  build.gradle
  src/main/java/com/moayo/moayoeats/backend/domain/user/dto/request/InfoUpdateRequest.java
  src/main/java/com/moayo/moayoeats/backend/domain/user/dto/request/PasswordUpdateRequest.java
  src/main/java/com/moayo/moayoeats/backend/domain/user/dto/request/SignupRequest.java
  src/test/java/com/moayo/moayoeats/backend/domain/user/dto/request/SignupRequestTest.java
  src/test/java/com/moayo/moayoeats/backend/domain/user/service/impl/UserServiceImplTest.java
  src/test/java/com/moayo/moayoeats/test/CommonTest.java
Labels: test
